const TYPE_SEAT = {
  NORMAL: "NORMAL",
  VIP: "VIP",
  DOUBLE: "DOUBLE",
};

export const ROOM1 = [
  [
    { name: "A1", type: TYPE_SEAT.VIP },
    { name: "A2", type: TYPE_SEAT.VIP },
    { name: "A3", type: TYPE_SEAT.VIP },
    { name: "A4", type: TYPE_SEAT.VIP },
    { name: "A5", type: TYPE_SEAT.VIP },
    { name: "A6", type: TYPE_SEAT.VIP },
    { name: "A7", type: TYPE_SEAT.VIP },
    { name: "A8", type: TYPE_SEAT.VIP },
  ],
  [
    { name: "B1", type: TYPE_SEAT.VIP },
    { name: "B2", type: TYPE_SEAT.VIP },
    { name: "B3", type: TYPE_SEAT.VIP },
    { name: "B4", type: TYPE_SEAT.VIP },
    { name: "B5", type: TYPE_SEAT.VIP },
    { name: "B6", type: TYPE_SEAT.VIP },
    { name: "B7", type: TYPE_SEAT.VIP },
    { name: "B8", type: TYPE_SEAT.VIP },
  ],
  [
    { name: "C1", type: TYPE_SEAT.NORMAL },
    { name: "C2", type: TYPE_SEAT.NORMAL },
    { name: "C3", type: TYPE_SEAT.NORMAL },
    { name: "C4", type: TYPE_SEAT.NORMAL },
    { name: "C5", type: TYPE_SEAT.NORMAL },
    { name: "C6", type: TYPE_SEAT.NORMAL },
    { name: "C7", type: TYPE_SEAT.NORMAL },
    { name: "C8", type: TYPE_SEAT.NORMAL },
  ],
  [
    { name: "D1", type: TYPE_SEAT.NORMAL },
    { name: "D2", type: TYPE_SEAT.NORMAL },
    { name: "D3", type: TYPE_SEAT.NORMAL },
    { name: "D4", type: TYPE_SEAT.NORMAL },
    { name: "D5", type: TYPE_SEAT.NORMAL },
    { name: "D6", type: TYPE_SEAT.NORMAL },
    { name: "D7", type: TYPE_SEAT.NORMAL },
    { name: "D8", type: TYPE_SEAT.NORMAL },
  ],
  [
    { name: "E1", type: TYPE_SEAT.NORMAL },
    { name: "E2", type: TYPE_SEAT.NORMAL },
    { name: "E3", type: TYPE_SEAT.NORMAL },
    { name: "E4", type: TYPE_SEAT.NORMAL },
    { name: "E5", type: TYPE_SEAT.NORMAL },
    { name: "E6", type: TYPE_SEAT.NORMAL },
    { name: "E7", type: TYPE_SEAT.NORMAL },
    { name: "E8", type: TYPE_SEAT.NORMAL },
  ],
  [
    { name: "F1", type: TYPE_SEAT.NORMAL },
    { name: "F2", type: TYPE_SEAT.NORMAL },
    { name: "F3", type: TYPE_SEAT.NORMAL },
    { name: "F4", type: TYPE_SEAT.NORMAL },
    { name: "F5", type: TYPE_SEAT.NORMAL },
    { name: "F6", type: TYPE_SEAT.NORMAL },
    { name: "F7", type: TYPE_SEAT.NORMAL },
    { name: "F8", type: TYPE_SEAT.NORMAL },
  ],
];

export const ROOM2 = [
  [
    { name: "A1", type: TYPE_SEAT.NORMAL },
    { name: "A2", type: TYPE_SEAT.NORMAL },
    { name: "A3", type: TYPE_SEAT.NORMAL },
    { name: "A4", type: TYPE_SEAT.NORMAL },
    { name: "A5", type: TYPE_SEAT.NORMAL },
    { name: "A6", type: TYPE_SEAT.NORMAL },
    { name: "A7", type: TYPE_SEAT.NORMAL },
    { name: "A8", type: TYPE_SEAT.NORMAL },
  ],
  [
    { name: "B1", type: TYPE_SEAT.NORMAL },
    { name: "B2", type: TYPE_SEAT.NORMAL },
    { name: "B3", type: TYPE_SEAT.NORMAL },
    { name: "B4", type: TYPE_SEAT.NORMAL },
    { name: "B5", type: TYPE_SEAT.NORMAL },
    { name: "B6", type: TYPE_SEAT.NORMAL },
    { name: "B7", type: TYPE_SEAT.NORMAL },
    { name: "B8", type: TYPE_SEAT.NORMAL },
  ],
  [
    { name: "C1", type: TYPE_SEAT.NORMAL },
    { name: "C2", type: TYPE_SEAT.NORMAL },
    { name: "C3", type: TYPE_SEAT.NORMAL },
    { name: "C4", type: TYPE_SEAT.NORMAL },
    { name: "C5", type: TYPE_SEAT.NORMAL },
    { name: "C6", type: TYPE_SEAT.NORMAL },
    { name: "C7", type: TYPE_SEAT.NORMAL },
    { name: "C8", type: TYPE_SEAT.NORMAL },
  ],
  [
    { name: "D1", type: TYPE_SEAT.VIP },
    { name: "D2", type: TYPE_SEAT.VIP },
    { name: "D3", type: TYPE_SEAT.VIP },
    { name: "D4", type: TYPE_SEAT.VIP },
    { name: "D5", type: TYPE_SEAT.VIP },
    { name: "D6", type: TYPE_SEAT.VIP },
    { name: "D7", type: TYPE_SEAT.VIP },
    { name: "D8", type: TYPE_SEAT.VIP },
  ],
  [
    { name: "E1", type: TYPE_SEAT.VIP },
    { name: "E2", type: TYPE_SEAT.VIP },
    { name: "E3", type: TYPE_SEAT.VIP },
    { name: "E4", type: TYPE_SEAT.VIP },
    { name: "E5", type: TYPE_SEAT.VIP },
    { name: "E6", type: TYPE_SEAT.VIP },
    { name: "E7", type: TYPE_SEAT.VIP },
    { name: "E8", type: TYPE_SEAT.VIP },
  ],
  [
    { name: "F1", type: TYPE_SEAT.DOUBLE },
    { name: "F2", type: TYPE_SEAT.DOUBLE },
    { name: "F3", type: TYPE_SEAT.DOUBLE },
    { name: "F4", type: TYPE_SEAT.DOUBLE },
    { name: "F5", type: TYPE_SEAT.DOUBLE },
    { name: "F6", type: TYPE_SEAT.DOUBLE },
    { name: "F7", type: TYPE_SEAT.DOUBLE },
    { name: "F8", type: TYPE_SEAT.DOUBLE },
  ],
];
